baseURL = "https://haomega.github.io/myblog/"
languageCode = "zh-hans"
title = "å°è±ªå°è±ª"
theme = "hugo-PaperMod"

layout = "archives"
url = "/archives"
summary = "archives"



[params]
  description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author = "å°è±ª"
  ShowReadingTime = true
  SetThemeAuto = true
  contentTypeName = "posts"
  defaultTheme = "auto"
  ShowShareButtons = false

  [params.profileMode]
  enabled = true
  title = "å°è±ª"
  imageUrl = "https://avatars2.githubusercontent.com/u/22785340?s=460&u=768b79b2ee648625819f815ebad0a74066a7f812&v=4"
  imageTitle = "hao"

  [[params.profileMode.buttons]]
  name = "Archives"
  url = "archives"

  [[params.profileMode.buttons]]
  name = "Tags"
  url = "tags"

  [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = "Welcome to my blog"


[menu]

  [[menu.main]]
    name = "Archives"
    url = "archives/"
    weight = 5

  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 10

